[book]
authors = ["Sa√∫l Valdelvira"]
language = "en"
src = "src"
title = "Compiler Documentation"

[output.html]
additional-js = ["theme/mdbook-grammar.js"]
additional-css = ["theme/mdbook-grammar.css"]

[preprocessor.grammar]

[preprocessor.plantuml]
plantuml-cmd="plantuml"

[output]
